-- Migration: Add dji_import_batches (lookup table for parcel import batches)
-- Date: 2026-07-15
-- Purpose: Cerrar el gap de CI — la tabla existe en db/schema.sql (canónico) y
--   los scripts hacen INSERT INTO dji_import_batches ... RETURNING id, pero
--   NUNCA se migró a supabase/migrations/. Resultado: en CI las migrations
--   que referencian public.dji_import_batches(id) fallaban silenciosamente
--   y dejaban la BD sin dji_parcels/dji_flights/dji_fumigations/etc. — y
--   todos los tests e2e y el smoke test explotaban.
--
-- Tipo de la columna id: bigint, alineado con dji_parcels.batch_id que la
-- referencia (bigint not null references public.dji_import_batches(id)).
-- db/schema.sql usa SERIAL (=int4) — esa inconsistencia quedó así en
-- setups manuales previos; en runtime funciona porque Postgres acepta
-- la comparación int4↔bigint pero el FK formal necesita tipos idénticos.
-- Esta migration estandariza en bigint.
--
-- Idempotente: usa IF NOT EXISTS para re-runs seguros.
--
-- Rollback: DROP TABLE public.dji_import_batches;
--           (antes DROP CONSTRAINT en dji_parcels.batch_id)

CREATE TABLE IF NOT EXISTS public.dji_import_batches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source        TEXT NOT NULL DEFAULT 'djiag',
  imported_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.dji_import_batches IS
  'Lookup de batches de import de DJI parcels/flights. Una fila por corrida '
  'del scraper o import manual. Referenciada por dji_parcels.batch_id, '
  'dji_flights.batch_id, etc.';

-- ============================================================
-- VERIFICACION post-migration
-- ============================================================
-- Esperado:
--   - 1 fila (o más si ya había inserts previos)
--   - Columnas: id (bigint), source (text), imported_at (timestamptz)
--
-- Query:
--   SELECT column_name, data_type
--   FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'dji_import_batches'
--   ORDER BY ordinal_position;
