-- Migration: Add dji_drone_models lookup and dji_parcels normalized table
-- Date: 2026-06-17
-- Phase: Option B - 1 row per field with flat columns
-- Rollback: DROP TABLE dji_parcels; DROP TABLE dji_drone_models;

-- ============================================================
-- DJI DRONE MODELS (lookup)
-- ============================================================
create table if not exists public.dji_drone_models (
  code int primary key,
  name text not null,
  manufacturer text not null default 'DJI',
  notes text
);

insert into public.dji_drone_models (code, name, manufacturer, notes) values
  (0,   'Sin asignar',         'DJI', 'No se detectó modelo de dron en el plan'),
  (72,  'Agras T16 / T20',     'DJI', 'Agras serie 16/20 — verificar con el operador'),
  (201, 'Agras T40 / T50',     'DJI', 'Agras serie 40/50 — verificar con el operador'),
  (210, 'Agras T70 / similar', 'DJI', 'Modelo no documentado — confirmar con el operador')
on conflict (code) do nothing;

-- ============================================================
-- DJI PARCELS (Opción B — modelo normalizado, 1 fila por campo)
-- ============================================================
create table if not exists public.dji_parcels (
  id                    bigint generated by default as identity primary key,
  batch_id              bigint not null references public.dji_import_batches(id) on delete cascade,
  external_id           text not null,
  land_name             text,
  field_type            text not null,
  declared_area_ha      numeric(10, 4),
  spray_area_m2         numeric(12, 2),
  drone_model_code      int references public.dji_drone_models(code) on delete set null,
  drone_model_name      text,
  spray_width_m         numeric(5, 2),
  work_speed_mps        numeric(4, 2),
  optimal_heading_deg   numeric(5, 2),
  radar_height_m        numeric(4, 2),
  edge_offset_m         numeric(4, 2),
  obstacle_offset_m     numeric(4, 2),
  climb_height_m        numeric(4, 2),
  no_spray_zone_m2      numeric(12, 2),
  droplet_size          int,
  sweep_direction       int,
  is_orchard            boolean not null,
  uses_side_spray       boolean,
  spray_geom            geometry(MultiPolygon, 4326),
  reference_point       geometry(Point, 4326),
  waypoints             geometry(MultiPoint, 4326),
  waypoint_count        int,
  source_url_geometry   text,
  source_url_parameter  text,
  source_url_waypoint   text,
  raw_geometry          jsonb,
  raw_parameter         jsonb,
  raw_waypoint          jsonb,
  fetched_at            timestamptz not null default now(),
  unique (batch_id, external_id)
);

create index if not exists idx_dji_parcels_batch_id    on public.dji_parcels(batch_id);
create index if not exists idx_dji_parcels_drone       on public.dji_parcels(drone_model_code);
create index if not exists idx_dji_parcels_field_type  on public.dji_parcels(field_type);
create index if not exists idx_dji_parcels_is_orchard  on public.dji_parcels(is_orchard);
create index if not exists idx_dji_parcels_spray_geom  on public.dji_parcels using gist (spray_geom);
create index if not exists idx_dji_parcels_waypoints   on public.dji_parcels using gist (waypoints);
create index if not exists idx_dji_parcels_ref_point   on public.dji_parcels using gist (reference_point);

-- ============================================================
-- DJI FUMIGATION SCHEDULE (preparación para notificaciones)
-- ============================================================
-- Una sola fila por parcela activa con la cadencia esperada.
-- Permite calcular "next_due_date" sin tener que escanear historial.
create table if not exists public.dji_fumigation_schedule (
  id                    bigint generated by default as identity primary key,
  parcel_id             bigint not null references public.dji_parcels(id) on delete cascade,
  crop_type             text not null,
  recommended_cadence_days int not null check (recommended_cadence_days > 0),
  last_fumigation_date  date,
  next_due_date         date,
  is_active             boolean not null default true,
  notes                 text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_dji_fumigation_schedule_parcel    on public.dji_fumigation_schedule(parcel_id);
create index if not exists idx_dji_fumigation_schedule_next_due on public.dji_fumigation_schedule(next_due_date) where is_active = true;
