-- Migration: Add dji_flights table for per-flight DJI sorties
-- Date: 2026-06-23
-- Phase: per-flight data enrichment from `flight_records?page=N` endpoint.
--
-- Por que necesitamos una tabla separada (no reutilizar dji_fumigations):
--   - dji_fumigations = evento de fumigacion (1 fila por (parcela, fecha))
--   - dji_flights     = sortie individual del drone (1 fila por vuelo)
--   - Un vuelo puede cubrir varias parcelas (caso edge), o ser un test/manual
--     que no fumigó nada. dji_flights es la fuente de verdad de "qué hizo el
--     drone", dji_fumigations es "qué se fumigó en cada finca".
--   - El join flights × fumigations se hace por (parcel_id, fecha).
--
-- Por que parcel_id nullable:
--   - Al insertar desde DJI todavia no sabemos la parcela (eso requiere un
--     spatial join con dji_parcels). Las filas llegan con parcel_id NULL
--     y se llenan en un paso posterior (scripts/spatial-join-flights-parcels.js).
--   - Tambien hay vuelos sin parcela (test, manual, etc.).
--
-- Por que (flight_id, source) UNIQUE:
--   - DJI garantiza flight_id unico globalmente. Lo usamos como dedupe key
--     junto con source para distinguir futuras fuentes (manual, otra plataforma).
--   - UPSERT idempotente: correr el importer N veces no duplica filas.

-- ============================================================
-- DJI FLIGHTS (sorties individuales del drone)
-- ============================================================
create table if not exists public.dji_flights (
  id                  bigint generated by default as identity primary key,
  flight_id           bigint      not null,                       -- DJI internal flight ID (e.g. 638640703)
  parcel_id           bigint      references public.dji_parcels(id) on delete set null,
  drone_serial        text,                                       -- DJI serial number (e.g. R1272065674)
  drone_nickname      text,                                       -- human name (e.g. AFM T40 1)
  pilot_name          text,                                       -- DJI team_name (e.g. breiner pelaez)
  flyer_name          text,                                       -- DJI flyer_name (often same as org)
  district            text,                                       -- reverse-geocoded municipality (may be null)
  location            text,                                       -- full reverse-geocoded address
  start_at            timestamptz not null,
  end_at              timestamptz  not null,
  duration_seconds    int         not null,
  area_m2             numeric(12, 2),                             -- new_work_area
  spray_usage_ml      int,                                        -- spray_usage (mL)
  work_speed_m_s      numeric(5, 2),                              -- work_speed
  spray_width_m       numeric(5, 2),                              -- spray_width
  radar_height_m      numeric(5, 2),                              -- radar_height
  manual_mode         boolean,
  mode_name           int,                                        -- DJI mode enum (0=manual, 4=spray, etc.)
  create_date         date,                                       -- YYYYMMDD from DJI (local-ish)
  lng                 numeric(10, 7),                             -- centroid longitude (WGS84)
  lat                 numeric(10, 7),                             -- centroid latitude (WGS84)
  notes               jsonb,                                      -- raw DJI response + extra metadata
  captured_at         timestamptz not null default now(),
  source              text        not null default 'djiag' check (source in ('djiag', 'manual', 'import')),
  unique (flight_id, source)
);

-- Indices para queries típicas del dashboard
create index if not exists idx_dji_flights_parcel_date
  on public.dji_flights(parcel_id, start_at desc)
  where parcel_id is not null;

create index if not exists idx_dji_flights_date
  on public.dji_flights(start_at desc);

create index if not exists idx_dji_flights_drone_serial
  on public.dji_flights(drone_serial);

create index if not exists idx_dji_flights_pilot
  on public.dji_flights(pilot_name)
  where pilot_name is not null;

-- Indice geografico: las queries de spatial join contra dji_parcels usan
-- ST_DWithin, asi que un GIST index sobre (lng, lat) acelera el matching.
-- Nota: usamos un point geometry construido on-the-fly porque no podemos
-- agregar una columna geometry sin backfill. El index seria:
--   create index idx_dji_flights_geo on public.dji_flights using gist (ST_MakePoint(lng, lat));
-- Lo dejamos para un paso de optimizacion posterior si hace falta.

-- Comentario: para queries tipo "flights por drone en el último mes",
-- el idx_dji_flights_drone_serial + idx_dji_flights_date son suficientes.
comment on table public.dji_flights is
  'Per-flight DJI sorties from kr-ag2-api flight_records endpoint. One row per drone sortie. parcel_id is filled via spatial join against dji_parcels using ST_DWithin(lng/lat, parcel_geom, 50m).';