-- Migration: Drop dji_field_catalog (QW4 del roadmap de auditoría 2026-06-28)
-- Date: 2026-06-28
-- Phase: Quick Win QW4 — cerrar doble modelo de parcelas
--
-- Por qué drop dji_field_catalog:
--   - dji_field_catalog es la versión legacy del catálogo (nombre, área en texto,
--     ubicación, fecha) sin geometría. Toda esa info vive en dji_parcels desde
--     la migración del 17/06 (Opción B).
--   - Solo se usaba para:
--       a) `getDashboardMetrics.totalAssets` → cambiar a COUNT(dji_parcels)
--       b) `import_djiag_data.js` enrich UPDATE → remover (DJI no expone el
--          área declarada por catálogo, queda NULL hasta input del operador)
--   - 162 filas (del batch del 17/06), dato no crítico — el operador puede
--     confirmar áreas en otro canal.
--
-- Por qué NO un ALTER TABLE … RENAME TO _legacy_xxx:
--   - Mantener la tabla con datos "por las dudas" es la receta para que en 6
--     meses esté stale y nadie sepa si los datos son buenos. Mejor backup
--     explícito en dji_legacy_snapshot y DROP limpio.
--
-- Por qué SÍ un snapshot antes del DROP:
--   - Reversibilidad. Si en 6 meses alguien dice "necesito el área_text
--     original del catálogo para algo", está en dji_legacy_snapshot.
--
-- Rollback:
--   CREATE TABLE dji_field_catalog AS SELECT
--     (payload->>'id')::int AS id,
--     (payload->>'batch_id')::int AS batch_id,
--     payload->>'field_type' AS field_type,
--     payload->>'field_name' AS field_name,
--     payload->>'area_text' AS area_text,
--     payload->>'location_text' AS location_text,
--     (payload->>'record_date')::date AS record_date,
--     payload->>'raw_text' AS raw_text
--   FROM dji_legacy_snapshot WHERE legacy_table = 'dji_field_catalog';

-- ============================================================
-- 1) Crear tabla de snapshots si no existe (genérica para futuras migraciones)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.dji_legacy_snapshot (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_table    text NOT NULL,
  snapshotted_at  timestamptz NOT NULL DEFAULT NOW(),
  payload         jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dji_legacy_snapshot_table
  ON public.dji_legacy_snapshot (legacy_table, snapshotted_at DESC);

-- ============================================================
-- 2) Snapshot de dji_field_catalog antes del drop
-- ============================================================
INSERT INTO public.dji_legacy_snapshot (legacy_table, payload)
SELECT
  'dji_field_catalog',
  to_jsonb(fc)
FROM public.dji_field_catalog fc;

-- ============================================================
-- 3) Drop dji_field_catalog + sus índices
-- ============================================================
DROP INDEX IF EXISTS public.idx_dji_field_catalog_batch_id;
DROP INDEX IF EXISTS public.idx_dji_field_catalog_date;
DROP TABLE IF EXISTS public.dji_field_catalog CASCADE;

COMMENT ON TABLE public.dji_legacy_snapshot IS
  'Snapshots inmutables de tablas dropeadas en migraciones. Cada fila = 1 row de la tabla original al momento del drop. Consultar WHERE legacy_table = ''<nombre>''';