-- PostGIS se instala en el schema default (public) — el image Docker
-- genérico postgis/postgis:16-3.4 (que usa CI) lo pone ahí, NO en un
-- schema `extensions` (eso es convención de Supabase). Por eso las
-- referencias a tipos deben ser sin prefijo (`geometry(...)`), no
-- `extensions.geometry(...)`. Ver gap del audit y CI runs
-- 29427837506 / 29428095775.
create extension if not exists postgis;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text
);

create table if not exists public.parcels (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  crop_type text not null,
  planting_date date not null,
  geom geometry(MultiPolygon, 4326) not null
);

create table if not exists public.flights (
  id bigint generated by default as identity primary key,
  parcel_id bigint not null references public.parcels(id) on delete cascade,
  date date not null,
  area_covered numeric(12, 2) not null check (area_covered >= 0),
  image_url text,
  footprint geometry(Polygon, 4326) not null
);

create index if not exists idx_parcels_client_id on public.parcels(client_id);
create index if not exists idx_flights_parcel_id on public.flights(parcel_id);
create index if not exists idx_parcels_geom on public.parcels using gist (geom);
create index if not exists idx_flights_footprint on public.flights using gist (footprint);
