-- Migration: Auth — tabla app_users para NextAuth (Credentials)
-- Date: 2026-06-28
-- Sprint: Sprint 3 Opcion A (single-tenant auth con roles)
--
-- Decisiones:
--   - Tabla separada (`app_users`, no `dji_*`) porque NO es data de DJI/AG.
--     La operadora es auth admin, no data scrapeada.
--   - bcrypt-hash del password, no plain. La columna es `password_hash` (no
--     `password`) para que cualquier SELECT accidental no filtre credenciales.
--   - email como ident (unique, citext es overkill para Opcion A) — single
--     tenant, ~5-10 usuarios max, no necesitamos nada mas.
--   - role como enum text con CHECK para evitar typos literales:
--       'admin'        → CRUD completo, gestiona fumigaciones, cadencias, etc.
--       'viewer'       → solo lectura, dashboards + mapa + history.
--     Si en el futuro se necesita un 'editor' o 'auditor', es un ALTER TYPE
--     trivial (sin modificar queries existentes que ya castean).
--   - `is_active boolean DEFAULT true` para poder desactivar usuarios sin
--     borrarlos (audit trail + revocacion rapida).
--   - `last_login_at timestamptz` para detectar cuentas abandonadas / abuso.
--   - `created_at` + `updated_at` para consistencia con dji_*.
--
-- Seed:
--   El primer admin se crea via `npm run auth:seed -- <email> <password>`
--   (script seed-admin-user.js). NO se mete por defecto en la migracion
--   para no tener una password hardcodeada en el historial de Git.
--
-- Rollback:
--   DROP TABLE IF EXISTS public.app_users CASCADE;

-- ============================================================
-- 1) Tabla app_users
-- ============================================================
create table if not exists public.app_users (
  id              bigint generated by default as identity primary key,
  email           text        not null unique,
  password_hash   text        not null,
  role            text        not null default 'viewer'
                    check (role in ('admin', 'viewer')),
  is_active       boolean     not null default true,
  last_login_at   timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Indices minimos (email ya es unique, eso crea indice automatico).
-- Un indice por role seria util solo si hubiera > 1000 users, irrelevante
-- para single-tenant de Opcion A.

-- ============================================================
-- 2) Trigger para updated_at
-- ============================================================
create or replace function public.app_users_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
  before update on public.app_users
  for each row execute function public.app_users_set_updated_at();

-- ============================================================
-- 3) Comentarios
-- ============================================================
comment on table public.app_users is
  'Usuarios del panel admin AeroAdmin AFM (Sprint 3 — single-tenant). Source of truth para NextAuth Credentials provider. NO contiene data scrapeada de DJI AG.';

comment on column public.app_users.password_hash is
  'bcrypt hash del password (cost factor 10). NUNCA devolver al cliente.';

comment on column public.app_users.role is
  'admin = CRUD completo. viewer = solo lectura. Aplicado en el middleware + UI components.';
