create extension if not exists postgis with schema extensions;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text
);

create table if not exists public.parcels (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  crop_type text not null,
  planting_date date not null,
  geom extensions.geometry(MultiPolygon, 4326) not null
);

create table if not exists public.flights (
  id bigint generated by default as identity primary key,
  parcel_id bigint not null references public.parcels(id) on delete cascade,
  date date not null,
  area_covered numeric(12, 2) not null check (area_covered >= 0),
  image_url text,
  footprint extensions.geometry(Polygon, 4326) not null
);

create index if not exists idx_parcels_client_id on public.parcels(client_id);
create index if not exists idx_flights_parcel_id on public.flights(parcel_id);
create index if not exists idx_parcels_geom on public.parcels using gist (geom);
create index if not exists idx_flights_footprint on public.flights using gist (footprint);
