-- Migration: Add dji_fumigations table for per-parcel fumigation events
-- Date: 2026-06-18
-- Replaces the placeholder dji_fumigation_schedule from the previous migration
-- with a real schedule + events table.

-- ============================================================
-- DJI FUMIGATION SCHEDULE (cadencia esperada por parcela)
-- ============================================================
create table if not exists public.dji_fumigation_schedule (
  id                        bigint generated by default as identity primary key,
  parcel_id                 bigint not null references public.dji_parcels(id) on delete cascade,
  crop_type                 text not null,
  recommended_cadence_days  int  not null check (recommended_cadence_days > 0),
  last_fumigation_date      date,
  next_due_date             date,
  is_active                 boolean not null default true,
  notes                     text,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  unique (parcel_id)
);

create index if not exists idx_dji_fumigation_schedule_parcel    on public.dji_fumigation_schedule(parcel_id);
create index if not exists idx_dji_fumigation_schedule_next_due on public.dji_fumigation_schedule(next_due_date) where is_active = true;

-- ============================================================
-- DJI FUMIGATIONS (eventos de fumigación por parcela)
-- ============================================================
create table if not exists public.dji_fumigations (
  id                bigint generated by default as identity primary key,
  parcel_id         bigint not null references public.dji_parcels(id) on delete cascade,
  fumigation_date   date not null,
  product_used      text,
  dose_l_per_ha     numeric(8, 2),
  area_fumigated_m2 numeric(12, 2),
  drone_code_used   int references public.dji_drone_models(code) on delete set null,
  duration_minutes  int,
  notes             text,
  recorded_by       text,
  recorded_at       timestamptz not null default now(),
  source            text not null default 'manual' check (source in ('manual', 'djiscraper', 'import'))
);

create index if not exists idx_dji_fumigations_parcel_date on public.dji_fumigations(parcel_id, fumigation_date desc);
create index if not exists idx_dji_fumigations_date       on public.dji_fumigations(fumigation_date desc);
